---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: event-listener-clusterrolebinding
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: event-listener-sa
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-listener-sa
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-listener
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-listener
  template:
    metadata:
      labels:
        app: event-listener
    spec:
      serviceAccountName: event-listener-sa
      volumes:
        - name: date-config
          hostPath:
            path: /etc/localtime
      containers:
        - name: event-listener
          ports:
            - containerPort: 8080
          image: registry.cn-beijing.aliyuncs.com/kunpengcloud/event-listener:4.0
          env:
            - name: PROJECT
              value: "大连清算"
            - name: TOEKN
              value: ""
            - name: ALERT_SOCKET
              value: "10.100.70.100:31111"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: date-config
              mountPath: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: event-listener
  namespace: default
  labels:
    name: event-listener
spec:
  selector:
    app: event-listener
  type: NodePort
  ports:
    - name: event-listener
      protocol: TCP
      port: 8080
      targetPort: 8080